#!/bin/bash

set -e -u

ROOT=$(cd $(dirname $0)/.. && pwd)

DEVDIR=/tmp/concourse-dev
DBDIR=$DEVDIR/db

[ -d $DBDIR ] || sudo -u postgres /usr/lib/postgresql/9.3/bin/initdb -U postgres -D $DBDIR -E UTF8 --no-local

exec sudo -u postgres /usr/lib/postgresql/9.3/bin/postgres -D $DBDIR -h 0.0.0.0 -p ${POSTGRES_PORT:-6543} "$@"
