#!/bin/bash

set -e -u

ROOT=$(cd $(dirname $0)/.. && pwd)

DEVDIR=/tmp/concourse-dev
KEYSDIR=$DEVDIR/keys

export GOPATH=$ROOT
export PATH=$ROOT/bin:$PATH

go install github.com/concourse/tsa/cmd/tsa

exec tsa \
  --atc-url http://0.0.0.0:8080 \
  --host-key $KEYSDIR/web/tsa_host_key \
  --peer-ip 0.0.0.0 \
  --authorized-keys $KEYSDIR/web/authorized_worker_keys \
  --session-signing-key $KEYSDIR/web/session_signing_key \
  "$@"
